events {
  worker_connections 1024;
}

http {
  upstream crawler {
    server crawler:8080;   # Docker Swarm resuelve el nombre "crawler" al servicio
  }

  server {
    listen 80;

    location / {
      proxy_pass http://crawler;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}